name: twitter_notification_for_slack

# トリガーイベント
on:
  # 1. main ブランチへのプッシュ: 通知がうざいから停止中
  # push:
  #   branches:
  #     - main
  # 2. GitHub 上の手動実行
  workflow_dispatch:
  # 3. crontab
  schedule:
    # 日-木 22:00 (UTC) -> 月-金 8:00 (JST)
    - cron: "0 22 * * *"

jobs:
  twitter_notification_for_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run twitter_notification_for_slack.py
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MY_AUTHOR_ID: ${{ secrets.MY_AUTHOR_ID }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_TWITTER_NOTIFICATION: ${{ secrets.WEBHOOK_URL_TWITTER_NOTIFICATION }}
          WEBHOOK_URL_TWITTER_NOTIFICATION_FOR_NOTION: ${{ secrets.WEBHOOK_URL_TWITTER_NOTIFICATION_FOR_NOTION }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python twitter_notification_for_slack.py
